config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :debit_cards, only: [:new, :create] 
  root to: 'debit_cards#new'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/debit_card.rb
# frozen_string_literal: true

require 'bcrypt'

class DebitCard < ApplicationRecord
  attr_encrypted :cvv, encode: true, encode_iv: true, encode_salt: true

  belongs_to :user
  validates :token, presence: { message: 'Token must be present' }
  validates :token, uniqueness: { scope: %i[exp_month exp_year], message: 'The card was declined' }
  validates :user, presence: { message: 'User must be present' }

  scope :default, -> { where(default_flg: true) }
  after_initialize { |record| record.default_flg = true }

  def make_non_default!
    self.default_flg = false
    save!
  end

  # Stub out payment call to Stripe. Single action instead of auth/capture process
  # 100 - Your payment has been accepted.
  # 203 - Your payment has been declined. Please re-check
  # with the providing bank
  def stub_perform_payment(_amount)
    card_number = '4242424242424242'
    token == BCrypt::Engine.hash_secret(card_number, Settings.encryption.bcrypt_salt) ? '100' : '203'
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :validatable

  has_many :debit_cards

  validates :email,
            uniqueness: true,
            format: { with: email_regexp },
            allow_blank: true,
            allow_nil: true

  validates :first_name, :last_name, presence: true

  def default_debit_card
    debit_cards.default.first
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  layout 'application'
end

app/controllers/debit_cards_controller.rb
# frozen_string_literal: true

class DebitCardsController < ApplicationController
  before_action :authenticate_user!

  def new
    @debit_card = current_user.default_debit_card
    @new_debit_card = current_user.debit_cards.build
  end

  def create
    prepare_debit_card
    respond_to do |format|
      make_payment
      format.js
    end
  end

  private def prepare_debit_card
    if params[:existing_card]
      @debit_card = current_user.default_debit_card
    else
      submission = DebitCardSubmission.new(
        current_user,
        debit_card_params.merge(card_number: params[:card_number])
      )
      if submission.valid?
        begin
          @debit_card = DebitCardCreator.new(submission).perform!
        rescue ActiveRecord::RecordInvalid => error
          @alert = error.record.errors.messages.values.join('\n')
        end
      else
        @alert = submission.errors.messages.values.join('\n')
      end
    end
  end

  private def make_payment
    return if @alert.present?
    result = @debit_card.stub_perform_payment(params[:amount])
    if result.to_i == 100
      @notice = 'You order has been completed!'
    else
      @alert = "The specified debit card number is invalid. Please check the number you've provided and try again"
    end
  end

  private def debit_card_params
    params.require(:card).permit(:cvv, :exp_month)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/debit_cards_helper.rb
# frozen_string_literal: true

module DebitCardsHelper
end

app/views/debit_cards/_existing_card.html.erb
<div class='card_form'>
  <%= form_tag debit_cards_path, remote: true, id: 'existing_card_form' do %>
    <%= hidden_field_tag "existing_card", true  %>   
    <%= hidden_field_tag "amount", 20  %>   
    <div class='control-group'>
      <div class='left'>
        <label>Cardholder</label>
        <%= text_field_tag 'card[first_name]', current_user.first_name, size: 15, disabled: true, id: 'existing_card_first_name'  %>
      </div>
      <div class='right'>
        <%= text_field_tag 'card[last_name]', current_user.last_name, size: 15, disabled: true, id: 'existing_card_last_name'  %>
      </div>
    </div>
    <div class='control-group'>
      <div class='left'>
        <label>Card Number</label>
        <%= text_field_tag 'card[card_number]', "**** #{card.last4}", maxlength: 16, disabled: true, id: 'existing_card_number' %>
      </div>
    </div>
    <div class='control-group'>
      <div class='left'>
        <label>Expiration Date</label>
        <%= text_field_tag 'card[expiration_date]', "#{card.exp_month}/#{card.exp_year}", disabled: true, id: 'existing_card_exp_month'  %>
      </div>
    </div>

    <div class='control-group'>
      <%= submit_tag "Use debit card", class: 'button', data: { disable_with: "Please wait..." } %>
    </div>

  <% end%>
</div>

app/views/debit_cards/_new_card.html.erb
<div class='card_form'>
  <%= form_tag debit_cards_path, remote: true, id: 'new_card_form'  do %>
    <%= hidden_field_tag "amount", 20  %>   
    <div class='control-group'>
      <div class='left'>
        <label>Cardholder</label>
        <%= text_field_tag 'card[first_name]', current_user.first_name, size: 15, disabled: true  %>   
      </div>
      <div class='right'>
        <%= text_field_tag 'card[last_name]', current_user.last_name, size: 15, disabled: true  %>   
      </div>
    </div>
    <div class='control-group'>
      <div class='left'>
        <label>Card Number</label>
        <%= text_field_tag :card_number, nil, maxlength: 16, placeholder: 'Enter card number...' %>
        <div class='error_message'></div>
      </div>
    </div>
    <div class='control-group'>
      <div class='left'>
        <label>CVV</label>
        <%= text_field :card, :cvv, maxlength: 3, size: 20, placeholder: 'CVV' %>   
        <div class='error_message'></div>
      </div>
    </div>
    <div class='control-group'>
      <div class='left'>
        <label>Expiration Date</label>
        <%= month_field(:card, :exp_month)%>
        <div class='error_message'></div>
      </div>
    </div>
    <div class='control-group'>
      <%= submit_tag "Submit new debit card", class: 'button', data: { disable_with: "Please wait..." }, id: 'submit_new_card_button' %>
    </div>

  <% end%>
</div>

app/views/debit_cards/create.html.erb
<h1>DebitCards#create</h1>
<p>Find me in app/views/debit_cards/create.html.erb</p>

app/views/debit_cards/create.js.erb
<% if @alert %>
  $(".messages").html("<%= escape_javascript(render partial: 'layouts/messages', locals: { alert: @alert }) %>")
<% else %>
  $(".messages").html("<%= escape_javascript(render partial: 'layouts/messages', locals: { alert: nil, notice: nil }) %>")
  $("#dialog").html('<p><%= @notice %></p>');
  $("#dialog" ).dialog();
<% end %>

app/views/debit_cards/new.html.erb
<h1>Checkout. Recurring Amount $20</h1>
<div id="tabs">
  <ul>
    <% if @debit_card %>
      <li><a href="#tabs-1">Existing Debit Card</a></li>
    <% end %>
    <li><a href="#tabs-2">New Debit Card</a></li>
  </ul>
  <% if @debit_card %>
    <div id="tabs-1">
      <%= render partial: 'existing_card', locals: { card: @debit_card } %>
    </div>
  <% end %>
  <div id="tabs-2">
    <%= render partial: 'new_card', locals: { card: @new_debit_card } %>
  </div>
</div>


<div id="dialog" title="Order status">
</div>

app/views/layouts/_messages.html.erb
<div class='messages'>
  <%- if notice %>
    <p class="notice"><%= notice %></p>
  <% end %>
  <%- if alert %>
    <p class="alert"><%= alert %></p>
  <% end %>
</div>

app/views/layouts/_top_navigation.html.erb
<div class='header'>
  <h1>Problem #1: E-commerce debit card page</h1>
  <% if current_user %>
    <ul class='user_info'>
      <li>Email: <%= current_user.email %></li>
      <li><%= link_to('Logout', destroy_session_path(current_user), { :method => :delete }) %></li>
    </ul>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PaymentGateway</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render :partial => 'layouts/top_navigation' %>
    <%= render :partial => 'layouts/messages' %>
    <div class='vcontainer'>
      <div class='hcontainer'>
        <div class='content'>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>